Added check option, to check that the cookie file ends in %, and that no fortune is longer than 72 characters

diff --git a/datfiles/Makefile b/datfiles/Makefile
--- a/datfiles/Makefile
+++ b/datfiles/Makefile
@@ -12,6 +12,23 @@ STRFILE=../util/strfile
 
 all: cookies o-cookies w-cookies
 
+check:
+	for i in $(COOKIES) ; \
+		do \
+			echo -n "Testing $$i..."; \
+			if ! tail -n 1 $$i | grep -q ^%$  ; then \
+			        echo " failed % check" ; \
+				echo "Fortune cookie file does not end in a single %" ; \
+				exit 1; \
+			fi;\
+			if egrep -q ".{72}." $$i ; then \
+				echo " failed length check"; \
+				echo "Fortune cookie file contains a line longer than 72 characters"; \
+				exit 1; \
+			fi; \
+			echo " passed " ;\
+		done;
+
 cookies: cookies-stamp
 
 o-cookies:
